name: RocketBoots
main: com.disabledhamster.bukkit.rocketboots.RocketBoots
description: Various rocket boots, fun and useful, for flying around your server
author: DisabledHamster
version: 0.3.7

commands:
    rocketboots:
        description: Disable or enable RocketBoots (for yourself)
        usage: /<command> [on|off]
    rb:
        # alias of /rocketboots
        description: Disable or enable RocketBoots (for yourself)
        usage: /<command> [on|off]